/**
 * EMI — HeroUI theme override
 * ===========================
 * Generated by `$impeccable document` from the `:root` token block in
 * `index.html` (the deployed PWA, which is the design authority — see
 * DESIGN.md). Every value here is an EMI token, not a HeroUI default.
 *
 * This file is the contract for the real build. The prototype itself does not
 * consume it: index.html hardcodes literals and declares `:root` as intent
 * only (exactly one `var()` call in the whole file). When the app is rebuilt
 * on HeroUI, this replaces that block.
 *
 * Usage — tailwind.config.ts:
 *   import { heroui } from "@heroui/theme"
 *   import { emiTheme } from "./heroui.theme"
 *   export default { plugins: [heroui(emiTheme)] }
 *
 * Deliberate divergences from HeroUI defaults are marked ⚠ with the reason.
 */

export const emiTheme = {
  defaultTheme: "light",
  // EMI is light-only. The cockpit usage scene is a bright, glare-heavy
  // environment; a dark theme has not been designed and must not be inferred.
  themes: {
    light: {
      colors: {
        // ── Ground ─────────────────────────────────────────────────────────
        // ⚠ HeroUI defaults `background` to #FFFFFF and puts content ON white.
        //   EMI inverts this: a cool grey airframe field carries white panels.
        //   This inversion is the system's core material idea — see the
        //   Flat Field Rule in DESIGN.md. Do not "fix" it back to white.
        background: "#EEF1F4",   // --canvas
        foreground: "#131A21",   // --ink

        // Surface ramp, lightest to deepest. content1 is the card.
        content1: "#FFFFFF",     // --surface  · every card, row, sheet
        content2: "#F7F9FB",     // --hover    · hover state on white surfaces
        content3: "#F2F3F5",     // --inset    · inset wells, recessed groups
        content4: "#ECEFF3",     // --line-soft · softest fills and inner rules

        // ⚠ HeroUI defaults `divider` to rgba(17,17,17,0.15) — a translucent
        //   grey that shifts with whatever is behind it. EMI uses one opaque
        //   hairline everywhere so borders stay identical on canvas, on white,
        //   and on the inset surfaces. It is load-bearing: 64 uses.
        divider: "#DDE2E8",      // --line
        focus: "#1466D6",        // --brand

        // ── Brand ──────────────────────────────────────────────────────────
        // ⚠ HeroUI default primary is #006FEE. EMI Blue is the brand blue and
        //   the only colour permitted to signal interactivity.
        primary: {
          50:  "#F4F8FC",
          100: "#EAF0FA",        // --brand-tint
          200: "#CEDDEE",
          300: "#AAC6E0",
          400: "#4C93EF",
          500: "#1466D6",        // --brand · DEFAULT
          600: "#0E4EA8",        // --brand-deep · hover / pressed
          700: "#0B3F87",
          800: "#093067",
          900: "#062450",
          DEFAULT: "#1466D6",
          foreground: "#FFFFFF",
        },

        // ── Neutral ────────────────────────────────────────────────────────
        // The ink ramp is only three steps: ink → ink-2 → muted. Hierarchy is
        // carried by these, not by font weight (see the Semibold Default Rule).
        default: {
          50:  "#F7F9FB",        // --hover
          100: "#F2F3F5",        // --inset
          200: "#ECEFF3",        // --line-soft
          300: "#DDE2E8",        // --line
          400: "#C2C9D1",
          500: "#8A97A4",        // muted metadata
          600: "#5A6672",        // --ink-2 · secondary text
          700: "#3B4652",
          800: "#252E38",
          900: "#131A21",        // --ink
          DEFAULT: "#DDE2E8",
          foreground: "#131A21",
        },

        // ── Semantic ───────────────────────────────────────────────────────
        // These are readouts of real state only — a checklist completed, a
        // proficiency band, an answer graded. Never categorisation or accent.
        // ⚠ All three are deeper and less saturated than HeroUI's defaults
        //   (#17C964 / #F5A524 / #F31260). EMI reads as clinical, not neon.
        success: {
          500: "#17A673",        // --ok
          DEFAULT: "#17A673",
          foreground: "#FFFFFF",
        },
        warning: {
          500: "#EBB236",        // --caution
          DEFAULT: "#EBB236",
          foreground: "#131A21",
        },
        danger: {
          500: "#E4483B",        // --alert
          DEFAULT: "#E4483B",
          foreground: "#FFFFFF",
        },
      },

      layout: {
        // ⚠ HeroUI's `large` radius is 14px. EMI's --r-lg is 16px and it is
        //   the system radius: 61 uses against 5 of 14px. Cards, rows, tiles
        //   and full-width buttons are all 16px, and card padding is 16px to
        //   match — the corner and the gutter are the same number.
        radius: {
          small:  "8px",         // --r-sm  ✅ matches HeroUI
          medium: "12px",        // --r-md  ✅ matches HeroUI
          large:  "16px",        // --r-lg  ⚠ HeroUI default is 14px
        },

        // ⚠ EMI's type scale sits one notch below HeroUI's throughout
        //   (11/12/14/15 against 12/14/16/18). Small, dense, and legible at
        //   arm's length on a kneeboard — not a desk app's scale.
        fontSize: {
          tiny:   "11px",        // --fs-xs
          small:  "12px",        // --fs-sm
          medium: "14px",        // --fs-md
          large:  "15px",        // --fs-lg
        },
        lineHeight: {
          tiny:   "1.25",
          small:  "1.3",
          medium: "1.35",
          large:  "1.35",
        },

        spacingUnit: 4,          // --sp-1 ✅ matches HeroUI
        borderWidth: {
          small:  "1px",         // the hairline — the system default
          medium: "1.8px",       // checkbox outlines, so they survive at 26px
          large:  "3px",
        },
        dividerWeight: "1px",
        disabledOpacity: 0.5,
        hoverOpacity: 0.9,
      },
    },
  },
}

/**
 * Tokens HeroUI's schema has no slot for. Apply via Tailwind's `extend`.
 * Values are from the same `:root` block; see DESIGN.md for the doctrine
 * governing when each shadow is permitted.
 */
export const emiExtend = {
  borderRadius: {
    xs:    "4px",    // --r-xs  · progress bars, thin rules, chips-in-chips
    xl:    "20px",   // --r-xl  · hero cards and all cards on the iPad canvas
    glass: "28px",   // the tab bar capsule — the only element at this radius
  },
  boxShadow: {
    // ⚠ HeroUI's `shadow-small` is a three-layer stack at ~0.06 alpha. EMI's
    //   sh-1 is roughly half that weight and is a border-softener, not a lift.
    //   Substituting HeroUI's scale here would silently undo the Earned
    //   Shadow Rule on all 41 resting surfaces.
    "sh-1": "0 1px 2px rgba(19,26,33,0.03)",
    "sh-2": "0 14px 34px -20px rgba(19,26,33,0.40)",
    "sh-3": "0 24px 56px -20px rgba(19,26,33,0.45)",
    "hero": "0 18px 40px -24px rgba(14,78,168,0.7)",
    "cta":  "0 10px 22px -12px rgba(14,78,168,0.8)",
    "glass":
      "0 14px 34px -10px rgba(19,26,33,0.34), 0 2px 8px rgba(19,26,33,0.08), inset 0 1px 0 rgba(255,255,255,0.6)",
  },
  fontSize: {
    // Heading sizes live outside HeroUI's four-slot layout scale.
    "2xs": "9px",    // --fs-2xs
    "xl":  "18px",   // --fs-xl
    "2xl": "22px",   // --fs-2xl
    "3xl": "25px",   // --fs-3xl · the screen title
  },
  spacing: {
    // --sp-1..12, all multiples of 4. Matches Tailwind's default scale.
    tap: "44px",     // --tap · minimum touch target, enforced via ::after
  },
  screens: {
    canvas: { raw: "(min-width:700px) and (min-height:700px)" },
    "canvas-wide": "1100px",
    "ipad-pro": { raw: "(min-width:1180px) and (min-height:800px) and (orientation:landscape)" },
  },
  maxWidth: {
    shell:  "440px",  // the phone shell
    canvas: "1180px", // the iPad content cap
    narrow: "772px",  // single-column screens on the big canvas
  },
}
